# -*- coding: utf-8 -*-
"""task1_cleaningandprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2hGUCbZqSaIuXmForbSBjBX5gaifoCs
"""





from google .colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('marketing_campaign.csv', sep='\t')

print("🔍 Missing Values (Before):\n", df.isnull().sum())
df = df.dropna(subset=['Income'])
print("\n🔍 Missing Values (After):\n", df.isnull().sum())

df = df.drop_duplicates()

df['Education'] = df['Education'].str.strip().str.lower()
df['Marital_Status'] = df['Marital_Status'].str.strip().str.lower()

df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format="%d-%m-%Y", errors='coerce')

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df['age'] = 2025 - df['year_birth']
df['dt_customer'] = pd.to_datetime(df['dt_customer'], errors='coerce')

non_object_columns = df.columns.difference(['education', 'marital_status', 'dt_customer'])
df[non_object_columns] = df[non_object_columns].apply(pd.to_numeric, errors='coerce')

print("\n Cleaned DataFrame Info:")
print(df.info())
print("\n First 5 Rows:\n", df.head())

df.to_csv('cleaned_marketing_campaign.csv', index=False)
print("\n Data cleaned successfully. File saved as cleaned_mall_customers.csv")

df.to_csv('cleaned_marketing_analysis.csv', index=False)
from google.colab import files
files.download('cleaned_marketing_analysis.csv')